### ISSUE TITLE
Some questions about code

### ISSUE THREAD

**Issue by geotyper** [jobtalle/SketchSquids#33]
try to rewrite code in c++, but have some questions about code:
in body.js:
```
Body.prototype.update = function(impulse) {
    this.brain.update();

    let input = 0;
    let output = 0;

    for (const appendage of this.appendages) {
        for (let i = 0; i < appendage.inputs; ++i)
            appendage.setInput(this.brain.outputs[output++].output, i);

        for (let i = 0; i < appendage.outputs; ++i)
            this.brain.inputs[input++].activation += appendage.getOutput(i);

        appendage.update(impulse);
    }
};
```
cant find where function getOutput(i) define.
and appendage.setInput declared as 
```
Tentacle.prototype.setInput = function(value) {
    this.head.setAnchor(this.position, this.delta, this.calculateDelta() + (2 * value - 1) * this.sign);
```
with one argument, not two.

in body constructor:
```
  switch (dna.appendages[appendage].object) {
            case DNATentacle:
```
why you switch on object case,  as understand appendages dont have another objects?

tentacle.js:
```
Tentacle.prototype.build = function() {
    let tail = this.head;

    for (let i = 0; i < this.length; ++i) {
        const spring = this.spring * Math.pow(1 - (i / (this.length - 1)) * 0.35, this.springPower);

        tail = new Segment(
            tail.position.copy().add(this.delta.copy().normalize().multiply(Tentacle.SPACING)),
            spring,
            Tentacle.SPACING,
            tail);
    }

    return tail;
};
```
in this function you made loop over length of tentacle, but return only one tail, so to find the finish tail you make segments, not read previous create?

**Comment by geotyper** [comment]
![Screenshot at 2020-08-14 20-44-27](https://user-images.githubusercontent.com/30755433/90277963-3e871e00-de6f-11ea-9c74-6b5f63d06af6.png)

**Comment by geotyper** [comment]
![Screenshot at 2020-08-14 22-49-08](https://user-images.githubusercontent.com/30755433/90307016-8f346080-dedb-11ea-97f2-810a7605e7bd.png)

**Comment by jobtalle** [comment]
The squid looks beautiful!

Some answers to your questions:

* `appendage.getOutput()` is not yet implemented. This is a placeholder that should work for sensor appendages, which output a signal. Because no outputs have that property, the function doesn't exist yet.

* The second parameter of setInput is indeed unused and can be removed.

* Tentacle is indeed the only appendage type, so the switch statement has only one case.

* The tentacle is a recursive chain of segments, so you only need to return the root one. Each segment contains a reference to the next segment unless it's the last one.

**Comment by geotyper** [comment]
https://youtu.be/l-oRMQwQjFw this link to video with squids
in first video place link to your article
and one more question:
you use some interest address method
```
Brain.prototype.getNeuron = function(axonIndex) {
    switch (axonIndex & ~DNAAxon.INDEX_MASK) {
        case DNAAxon.FLAG_INPUT:
            return this.inputs[axonIndex & DNAAxon.INDEX_MASK];
        case DNAAxon.FLAG_NEURON:
            return this.neurons[axonIndex & DNAAxon.INDEX_MASK];
        case DNAAxon.FLAG_OUTPUT:
            return this.outputs[axonIndex & DNAAxon.INDEX_MASK];
    }
};
where can read about this, why you dont use "normal flags" not boolean mask?
```

**Comment by jobtalle** [comment]
The variable `axonIndex` actually contains both an index and flags. The flags and mask are defined as follows:

```
DNAAxon.INDEX_MASK = 0x0FFFFFFF;
DNAAxon.FLAG_INPUT = 0x10000000;
DNAAxon.FLAG_NEURON = 0x20000000;
DNAAxon.FLAG_OUTPUT = 0x40000000;
```

So what's happening is that the first 28 bits of a 32 bit integer are used for storing an integer (all bits masked by `INDEX_MASK`), and then there are three possible flags stored in that integer as well. By doing `axonIndex & ~DNAAxon.INDEX_MASK`, you only get the part that contains the flags.

**Comment by geotyper** [comment]
Thanks, wait  for your new projects! 
this my telegram channel https://t.me/nonFormalAICupsDiscussions/ there some pictures from developing my hobby projects
